Iter15
gerasimovpavel/shortener pull request #17
Opened 2023-11-21 09:57 UTC by gerasimovpavel

2023-11-27 14:08 UTC, capsulated requested changes
Всё в общем хорошо, но, скорее всего, опечатка в одном месте, где парсится строка подключения к базе - надо пофиксить.

И если получится сделать один запрос из цикла - будет вообще 🔥

2023-11-27 14:08 UTC, capsulated commented on internal/storage/postgres.go
> +		config.MaxConns = 50
❌ Очень похоже на опечатку при автозамене. Если конфиг не спарсится, то не будет работать же. В `ps` хранится connection string, да? Переназвать бы её в `connStr`, чтобы сразу понятно было, что это такое

2023-11-27 14:08 UTC, capsulated commented on internal/storage/postgres.go
> +	for _, data := range urls {
⚠️ Плохо, что много SQL запросов в цикле. Лучше сделать один. Если успеешь разобраться - будет супер (по желанию)

2023-11-28 05:19 UTC, gerasimovpavel commented on internal/storage/postgres.go
> +	for _, data := range urls {
#Для эффективного проставления флага удаления в БД используйте множественное обновление (batch update).

такое задание было

2023-11-30 20:54 UTC, capsulated approved these changes
Всё супер!

2023-11-30 20:54 UTC, capsulated commented on internal/storage/postgres.go
> +	for _, url := range urls {
Ага, всё верно, типа того. Я тоже именно так и делал, но это не очень красиво конечно, зато нагрузка на базу снижается. Есть и другие варианты

2024-02-06 04:50 UTC, merged