Iter20
gerasimovpavel/shortener pull request #21
Opened 2024-02-08 08:08 UTC by gerasimovpavel

2024-02-10 01:45 UTC, capsulated requested changes
1. Покрытие тестами: 54.6%, а по требованиями: не менее 55% 😄 Ну это мелочь, фиксить по желанию 
2. Необходимо в `godoc` подробнее указать, какие из анализаторов используются.   Cамому можно ничего не придумывать и просто скопировать имена, а лучше, имена с кратким описанием. И добавить инструкцию по запуску (можно, в принципе, даже на русском) "_Добавьте документацию в формате godoc, подробно опишите в ней механизм запуска multichecker, а также каждый анализатор и его назначение."_(c)
3. По анализаторам `golang.org/x/tools/go/analysis` только часть анализаторов проверяется? По заданию все нужны (если с какими-то проблемы - пиши в доку, попробуем разобраться)
4. По statictest, я так понимаю, все анализаторы используются, и SA и все остальные? 
5. И "_двух или более любых публичных анализаторов на ваш выбор."_(c) не хватает. К ним тоже описаловку краткую, что они там делаю. Можно найти что-то кастомное на просторах github

2024-02-10 11:33 UTC, gerasimovpavel commented
1. У меня показывает 
<img width="324" alt="image" src="https://github.com/gerasimovpavel/shortener/assets/18548523/5b583d16-3ae1-4927-a53b-7de09fd237f2">
2. Добавил
3. Добавил
4. Исправил
5. Добавил

2024-02-13 01:34 UTC, capsulated requested changes
Вроде всё ок, глядя по коду, но...

Cгенеренная дока пустая получилась. Её бы пофиксить и будет идеально (вроде бы... комменты плохо читаются)

![image](https://github.com/gerasimovpavel/shortener/assets/10791403/44cdaf87-75a9-401a-82c6-4934dba3affa)

2024-02-13 09:53 UTC, gerasimovpavel commented
<img width="1232" alt="image" src="https://github.com/gerasimovpavel/shortener/assets/18548523/5a6e7e84-529e-4396-90a9-c872467186ed">

2024-02-13 13:52 UTC, capsulated approved these changes
Да, появилась дока. Но конечно, не сильно проработана, видно, что торопишься очень. Или энтузиазм пропал?

Порефактори, если будет время: доку проработать, чтобы красивая и читабельная была, и анализаторы можно по пакетам раскидать, типа `base`, `style`, `static`, `custom`

А так, вообщем ок, апрувлю

2024-02-20 04:36 UTC, merged